services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "${RPI_TAILSCALE_IP}:9443:9443" #Portainer 
      - "${RPI_TAILSCALE_IP}:8080:8080" #NextCloud
      - "${RPI_TAILSCALE_IP}:5230:5230" #Memos
      - "${RPI_TAILSCALE_IP}:5005:5005" #Flame
      - "${RPI_TAILSCALE_IP}:8081:8081" #Quartz
      - "${RPI_TAILSCALE_IP}:3000:3000" #PsiTransfer
      - "${RPI_TAILSCALE_IP}:8888:8888" #Ntfy
      - "${RPI_TAILSCALE_IP}:2283:2283" #Immich
      - "${RPI_TAILSCALE_IP}:9090:9090" #Linkding
      - "${RPI_TAILSCALE_IP}:4533:4533" #Navidrome
    volumes:
      - ${USER_HOME}/server/self-hosting/stacks/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${USER_HOME}/server/docker-data/caddy/config:/config
      - ${USER_HOME}/server/docker-data/caddy/data:/data
      - ${USER_HOME}/server/docker-data/certs:/certs:ro
    environment:
      - TAILSCALE_DOMAIN=${TAILSCALE_DOMAIN}
    networks:
      - service-network
 
networks:
  service-network:
    external: true
